# Generated by Django 5.2.4 on 2025-07-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_registration_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
